services:
  postgres:
    container_name: assessment_container
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"


  cat-app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - :/app/configs/prod-config.yaml
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8085:8085"