version: '3.8'

# Sensible data here because of development speed
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cat_app
    ports:
      - "8085:8085"
    depends_on:
      - postgres
    volumes:
        - ./configs:/assessment/configs
    environment:
      - POSTGRES_USER=themaxs
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=test-assessment
    networks:
      - app-network

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge