services:
  db:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U test_assessment" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cat_app
    ports:
      - "8085:8085"
    env_file:
      - .env
    networks:
      - app-network


volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge